New folder
================

=== UNARCHIVE AND STRUCTURE ===
OK!

=== COMPILE ===
Skipping (python)

=== EVALUATION ===

== ID3 ==
  Passed 0 / 16 tests.

- Failed test: python solution.py volleyball.csv volleyball_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py volleyball.csv volleyball_test.csv 1
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py titanic_train_categorical.csv titanic_test_categorical.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py titanic_train_categorical.csv titanic_test_categorical.csv 2
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py logic_small.csv logic_small_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py logic_small.csv logic_small_test.csv 1
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f2_train.csv heldout_logic_f2_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f2_train.csv heldout_logic_f2_test.csv 3
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f3_train.csv heldout_logic_f3_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f3_train.csv heldout_logic_f3_test.csv 1
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f4_train.csv heldout_logic_f4_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_logic_f4_train.csv heldout_logic_f4_test.csv 2
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_singlefeat_train.csv heldout_singlefeat_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_small_train.csv heldout_small_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py heldout_unseen_featurevalue_train.csv heldout_unseen_featurevalue_test.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


- Failed test: python solution.py titanic_train_categorical.csv titanic_heldout_categorical.csv
Execution failed with error (process returned non-zero exit code):
Traceback (most recent call last):
  File "solution.py", line 513, in <module>
    main()
  File "solution.py", line 274, in main
    input_lines = [i for i in open(r"{}".format(clauses_path), encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'None'


=== TOTAL RESULTS ===
0 / 16 tests passed. (0.0%)

